### PR TITLE
Update author name to Sencrop

### PR DESCRIPTION
**Pull request by piitaya**
My name (and my personal e-mail was here 🙈)

### CODE REVIEW

**Comment by piitaya** [comment]
Hi @Oupsla 👋
Do you think this can be merged? 😁

**Comment by Oupsla** [comment]
Hello @piitaya 
Oops, of course it can be, thanks 😄 

(hope that all is going well for you)

**Comment by piitaya** [comment]
I should probably go to txa to get news (if it still exists 😅). Or come to the office.

**Comment by Oupsla** [comment]
> I should probably go to txa to get news (if it still exists 😅). Or come to the office.

Of course it still exists haha
And you are welcome to the office (https://maps.app.goo.gl/o3EEE3AVRuMrQyEXA), we have foodtrucks now at noon time 😄

**Pull request merged**
